### ISSUE TITLE
Plugin install but can't find post build action

### ISSUE THREAD

**Issue by emoshaya-cognito** [BogdanLivadariu/bootstraped-multi-test-results-report#7]
Hi,

I'm using:
Jenkins ver. 1.640
bootstraped-multi-test-results-report 1.4.5

I've created both maven and freestyle builds but I can't for the life of me find publish cucumber report with handlebars in the post build options. Could you please explain what i'm doing wrong?

**Comment by emoshaya-cognito** [comment]
also when I got to:
https://wiki.jenkins-ci.org/display/JENKINS/Bootstraped+Multi+Test+Results+Report

and click on the Github Link https://github.com/jenkinsci/bootstraped-multi-test-results-report-plugin

it seems to be broken I get a 404 page

**Comment by BogdanLivadariu** [comment]
Hi @emoshaya-cognito 

are there eny errors in the jenkins logs ?

feel free to join: https://gitter.im/BogdanLivadariu/bootstraped-multi-test-results-report

chatting usually goes allot faster there :)

**Comment by BogdanLivadariu** [comment]
for future reference, here is the log, @emoshaya-cognito  shared on gitter.

this might come in handy, if others are scanning for closed isues
```
WARNING: Failed to scout com.github.bogdanlivadariu.jenkins.reporting.rspec.RSpecTestReportPublisher$DescriptorImpl
java.lang.InstantiationException: java.lang.UnsupportedClassVersionError: com/github/bogdanlivadariu/jenkins/reporting/rspec/RSpecTestReportPublisher$DescriptorImpl : Unsupported major.minor version 52.0
at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:666)
at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:382)
at hudson.ExtensionList.load(ExtensionList.java:349)
at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
at hudson.ExtensionList.iterator(ExtensionList.java:156)
at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:381)
at hudson.ExtensionList.load(ExtensionList.java:349)
at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
at hudson.ExtensionList.getComponents(ExtensionList.java:167)
at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:185)
at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
at hudson.ExtensionList.iterator(ExtensionList.java:156)
at hudson.ExtensionList.get(ExtensionList.java:147)
at com.cloudbees.jenkins.GitHubPushTrigger$DescriptorImpl.get(GitHubPushTrigger.java:320)
at org.jenkinsci.plugins.github.migration.Migrator.migrate(Migrator.java:41)
at org.jenkinsci.plugins.github.GitHubPlugin.postInitialize(GitHubPlugin.java:39)
at hudson.PluginManager$2$1$2.run(PluginManager.java:403)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
at jenkins.model.Jenkins$8.runTask(Jenkins.java:913)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedClassVersionError: com/github/bogdanlivadariu/jenkins/reporting/rspec/RSpecTestReportPublisher$DescriptorImpl : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:801)
at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1185)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
... 25 more
Dec 11, 2015 9:13:20 AM hudson.ExtensionFinder$Sezpoz scout
WARNING: Failed to scout com.github.bogdanlivadariu.jenkins.reporting.cucumber.CucumberTestReportPublisher$DescriptorImpl
java.lang.InstantiationException: java.lang.UnsupportedClassVersionError: com/github/bogdanlivadariu/jenkins/reporting/cucumber/CucumberTestReportPublisher$DescriptorImpl : Unsupported major.minor version 52.0
```

__This looks like you don't have JAVA 8 installed on the jenkins host.__


@emoshaya-cognito after you install java 8 onto the host, if this solves your problems, can you close this issue ?

**Comment by emoshaya-cognito** [comment]
sure, I'll close it straight after

**Comment by emoshaya-cognito** [comment]
Thanks this was resolved after I updated to Java 8

**Comment by emoshaya-cognito** [comment]
Appreciate your help!
